### ISSUE TITLE
Is this still working? 10/22/21 Not working for me..

### ISSUE THREAD

**Issue by techmechanic1** [iganeshk/standardnotes-extensions#26]
After setup when I go to https://my-domain.com/extensions/index.json I get   404 Not Found   nginx/1.18.0 (Ubuntu)..

**Comment by lazios** [comment]
Maybe you got some error in your nginx config but if you don't figure it out you can use https://github.com/kylejbrk/standard-notes-open-extended aswell. You would then need to paste "https://kyleburke.net/standard-notes-open-extended" in the 
**_Enter Your Extended Activation Code_** box.

**Comment by gyaneesh** [comment]
> After setup when I go to https://my-domain.com/extensions/index.json I get 404 Not Found nginx/1.18.0 (Ubuntu)..

You might want to check your root path, verify it's accessible by nginx process owner

**Comment by techmechanic1** [comment]
Thanks for your input so far! I still haven't got it to work, if I create a test.js file in the public folder I can open it by going to https://my-domain.com/extensions/test.js. So I believe the permissions should be right.??
