### ISSUE TITLE
Anyone else running into "No subscriptions" errors when using self-hosted Standard Notes editors?

### ISSUE THREAD

**Issue by xthursdayx** [iganeshk/standardnotes-extensions#33]
I do not have a subscription, since I self-host all of the extensions I use in Standard Notes using this repo. However, after the most recent update to Standard Notes Desktop, all of the editors created by Standard Notes (e.g. Bold Editor or Simple Task Editor) no longer work and there is a banner at the top of the editor window that says:
> You do not have an active subscription.
> Simple Task Editor is in a read-only state.

Strangely, other SN extension created by SN organization, such as Action Bar and their themes, still seem to work. 

Is anyone else running into problem? I'm hoping that SN's open-source extensions will no longer be self-hostable. This appears to be related to this issue in the SN Desktop repo: https://github.com/standardnotes/desktop/issues/789

Either way, with the most recent versions of Standard Notes Desktop and Standard Notes Web the instructions in the README.md are no longer correct. If you try to add your `https://your-domain.com/extensions/index.json` endpoint in the `Activate Offline Subscription` box in `Preferences > General > Advanced Settings` you will get the following error: 
```
An unknown issue occurred during offline activation. Please try again.
``` 
This requires the user to manually add each extension using the extensions specific `index.json`, for example, `https://your-domain.com/extensions/append-editor/index.json`. I believe that this is why the extensions created by Standard Notes are no longer working, despite being self-hosted.

**Comment by Saldef** [comment]
I am on Pro Subscription plan (The highest), and running into the same 'No Subscription' problem on SN Web, FileSafe is on read-only and asking me to upgrade my subscription, and whenever I switch from a custom editor to a native editor an error message appears saying `An extension is trying to communicate with Standard Notes, but there is an error establishing a bridge. Please restart the app and try again.`

**Comment by xthursdayx** [comment]
Strange... this seems to be happening to people regardless of their subscription status. From the issues I've seen on the SN repos, it seems like the devs over there usually ask subscriptions users to email them to sort it out, so I'm not sure what this means for those of us who self-host the components.

**Comment by xthursdayx** [comment]
Just an update from the SN devs:

> 3rd party extensions do not require a subscription. However the way we detect if an extension is 3rd party or 1st party is by its identifier. So if the identifier is "org.standardnotes.bold-editor", regardless of where it's hosted, it will be treated as a first party extension and will enter into subscription validation logic.

> You'll want to change the identifier for self-hosted extensions if they are our extensions and have the appropriate OS license.

I'll work on fixing this in the repo and push a PR.

**Comment by ashutoshsaboo** [comment]
> Just an update from the SN devs:
> 
> > 3rd party extensions do not require a subscription. However the way we detect if an extension is 3rd party or 1st party is by its identifier. So if the identifier is "org.standardnotes.bold-editor", regardless of where it's hosted, it will be treated as a first party extension and will enter into subscription validation logic.
> 
> > You'll want to change the identifier for self-hosted extensions if they are our extensions and have the appropriate OS license.
> 
> I'll work on fixing this in the repo and push a PR.

Do you have the github issue link where SN team mentioned this?

**Comment by xthursdayx** [comment]
Looks like you already found it, but it's here: https://github.com/standardnotes/desktop/issues/789#issuecomment-984716573

**Comment by jonwsoto** [comment]
Hmm noticing this is a problem for everyone now… so you think this will be the ongoing pattern by the company? Break something to push the self hosted toward a subscription? I feel this was the last straw for me and just doesn’t seem safe keeping my notes here.

**Comment by xthursdayx** [comment]
There is a workaround involving changing the extension IDs that I added to PR https://github.com/iganeshk/standardnotes-extensions/pull/35, but yes, my sense is that the SN devs are primarily focused enforcing subscriptions and limiting access to non-subscription users while streamlining the experience for their subscription users. Given that the base code for Standard Notes web, desktop, mobile, syncserver, all the editors, etc. is open-source, I think that there will continue to be ways to work around the roadblocks and self-host the service, but it does speak to the priorities of the developers.

**Comment by jonwsoto** [comment]
Much appreciated, just seems to be so many hurdles to jump through to keep things going, had a good workflow going. So to install these, it is a similar process to just linking the .json end point url like what iganeshk describes in his tutorial?

**Comment by xthursdayx** [comment]
Yep, it would be the same process. The only thing that would change would be the internal extension ID.

**Comment by jonwsoto** [comment]
I managed to get them updated. Had to manually install each of the extension URLs, it would not let me install the single URL. The only thing I notice is that my 2FA token appears to have transferred over but under the settings it is acting like I can setup a new one. But when I do try to setup a new token it doesn’t let me for some reason. Anyways my old token works well but this seems kind of concerning. You have any similar experience?

**Comment by xthursdayx** [comment]
> I managed to get them updated. Had to manually install each of the extension URLs, it would not let me install the single URL. The only thing I notice is that my 2FA token appears to have transferred over but under the settings it is acting like I can setup a new one. But when I do try to setup a new token it doesn’t let me for some reason. Anyways my old token works well but this seems kind of concerning. You have any similar experience?

Sorry, I missed this somehow. I don't actually use TokenVault so I can't speak to that, sorry. But I do have the same issue with having to add each extension URL individually. My PR updates the main README accordingly.

**Comment by jonwsoto** [comment]
It’s not tokenvault I am referring to. I mean the two factor authentication to add to your main account login. 

This particular extension 

https://github.com/iganeshk/standardnotes-extensions/blob/master/extensions/mfa-link.yaml

basically it seems to install but does not seem to allow you secure your account by adding to an Authenticator. It gives some sort of error stating can’t communicate. I am not sure if it is directing to their servers versus your own.

**Comment by xthursdayx** [comment]
> It’s not tokenvault I am referring to. I mean the two factor authentication to add to your main account login. 

Ahhh, I understand what you mean now. I haven't been using 2FA, so hadn't come across this problem. I think this should probably be noted as a separate issue from the editor "no active subscription" errors, but I will look into it when I have a chance.

**Comment by xthursdayx** [comment]
Closing this as PR https://github.com/iganeshk/standardnotes-extensions/pull/35 will be merged shortly. If anyone is still having issues feel free to open a new issue.
