### ISSUE TITLE
sn-nord-theme repo spelling error

### ISSUE THREAD

**Issue by trinsic** [iganeshk/standardnotes-extensions#38]
Both urls are missing an 'e' on the end of them.
github: marc-sensenich/sn-nord-them
marketing_url: https://github.com/marc-sensenich/sn-nord-them

True urls:
github: marc-sensenich/sn-nord-theme
marketing_url: https://github.com/marc-sensenich/sn-nord-theme

**Comment by xthursdayx** [comment]
> Both urls are missing an 'e' on the end of them.
> 
> github: marc-sensenich/sn-nord-them
> 
> marketing_url: https://github.com/marc-sensenich/sn-nord-them
> 
> 
> 
> 
> 
> True urls:
> 
> github: marc-sensenich/sn-nord-theme
> 
> marketing_url: https://github.com/marc-sensenich/sn-nord-theme
> 
> 

Oh, sorry, that extension should have been removed in the last merge, but I missed it. This repo no longer uses marc-sensenich's nord theme since I was running into issues getting it to build correctly. I've since created my own Nord-based theme and added it.
