### ISSUE TITLE
After updating standardnotes server, problem #33 is reappearing.

### ISSUE THREAD

**Issue by BobWs** [iganeshk/standardnotes-extensions#41]
Hi,
I have updated my standardnotes server and desktop app to the latest version and the problem #33 with the extension is back. I followed all the steps and reinstalled all the extensions, but I keep getting the message that I don't have a valid subscription and some extension are under the payment plan.

Does anyone have this also after updating, and is there a new trick or solution to get it working again?

**Comment by xthursdayx** [comment]
Sorry for the delay. I haven't noticed any issues with the extensions and also using the latest versions of the server and desktop app. You might try removing all of your extensions and re-adding them to see if they work again. If not, then there may be a new issue to deal with.

**Comment by BobWs** [comment]
> Sorry for the delay. I haven't noticed any issues with the extensions and also using the latest versions of the server and desktop app. You might try removing all of your extensions and re-adding them to see if they work again. If not, then there may be a new issue to deal with.

Thanks for replying.
I have already tried that, I have removed all the extensions and re-entered them again, but then I get the “you don’t have a valid subscription” message. When I revert back to and older version of the desktop app then everything works fine, no warning messages and the extensions just work.

I get the valid subscription warning on the latest version of the desktop app and standardnotes web. Updated iOS apps doesn’t show any warning. So I’m a bit lost here. 

For now I stick to the older version of the desktop app until I find the solution.

**Comment by BobWs** [comment]
I have tried it again and now most of the extensions work with the latest desktop version, but only folders-component extension doesn't work. I keep getting the upgrade to premium message.
![Screen_Shot](https://user-images.githubusercontent.com/5485820/156889018-e6d5fc7b-5496-45db-bced-024f7aea75c6.png)

Anyone else have also experienced this problem?
Any thoughts how to fix this?

**Comment by doakyz** [comment]
SN devs have recently posted this, might help troubleshoot the issue. 

https://docs.standardnotes.com/self-hosting/subscriptions/

**Comment by BobWs** [comment]
> SN devs have recently posted this, might help troubleshoot the issue.

Yes thanks I know already implemented it.

**Comment by valantur** [comment]
Sorry to harp on this, but I ran into this same issue today. The desktop client of standard notes allows me to install the self-hosted extensions on my cloned copy of this repo, but then whenever I want to enable an extension it says I need to purchase a subscription plan.

I'm selfhosting my server too btw. Any idea how to fix this?

Thanks!

**Comment by BobWs** [comment]
> Sorry to harp on this, but I ran into this same issue today. The desktop client of standard notes allows me to install the self-hosted extensions on my cloned copy of this repo, but then whenever I want to enable an extension it says I need to purchase a subscription plan.
> 
> I'm selfhosting my server too btw. Any idea how to fix this?
> 
> Thanks!

See comments here https://github.com/standardnotes/standalone/issues/64#issuecomment-1064719310 how to fix it!

**Comment by valantur** [comment]
oh bummer as far as I can tell I can't apply this fix cause it involves adding some entries to the database and I'm currently using an alternate server: [https://github.com/mdouchement/standardfile](url).
This server uses BoltDB as database, so all MYSQL commands are not compatible.
Someone opened a ticket on that project a couple of guys are trying to fix it.

Thanks anyway!

**Comment by BobWs** [comment]
Okay, good luck!
