### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by akhiljalagam** [iganeshk/standardnotes-extensions#42]
I used the nginx template from README.md but still, I'm getting this error on chrome

`Access to XMLHttpRequest at 'https://notes.mydomain.com/extensions/sn-nord-theme/index.json' from origin 'https://app.standardnotes.com' has been blocked by CORS policy: Request header field x-application-version is not allowed by Access-Control-Allow-Headers in preflight response.`

my nginx configuration
```
server {
    server_name notes.mydomain.com;

    location / {
        proxy_pass http://127.0.0.1:3000; # syncing-server address
    }

client_max_body_size 50M;

location ^~ /extensions {
                autoindex off;
                alias /opt/standardnotes/standardnotes-extensions/public;
                # CORS HEADERS
                if ($request_method = 'OPTIONS') {
                   add_header 'Access-Control-Allow-Origin' '*';
                   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                   #
                   # Custom headers and headers various browsers *should* be OK with but aren't
                   #
                   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                   #
                   # Tell client that this pre-flight info is valid for 20 days
                   #
                   add_header 'Access-Control-Max-Age' 1728000;
                   add_header 'Content-Type' 'text/plain; charset=utf-8';
                   add_header 'Content-Length' 0;
                   return 204;
                }
                if ($request_method = 'POST') {
                   add_header 'Access-Control-Allow-Origin' '*';
                   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                   add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
                }
                if ($request_method = 'GET') {
                   add_header 'Access-Control-Allow-Origin' '*';
                   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                   add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
                }
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/notes.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/notes.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

To reproduce it , click on install:
nginx/1.18.0
Browser: Google Chrome	100.0.4896.88 (Official Build) (64-bit)
headers: add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
![image](https://user-images.githubusercontent.com/21128035/163783557-234a0809-f4d4-4433-ab2b-5b16fc6a9d39.png)

**Comment by xthursdayx** [comment]
I'm sorry, but I'm not sure how to troubleshoot your problem, as I'm unable to reproduce it. To me, the CORS error you're getting makes it sound like perhaps you have something in your `options-ssl-nginx.conf` that is adding the header `x-application-version`, which is not allowed according to the `Access-Control-Allow-Headers` settings. You can try adding `x-application-version` to the two occurrences of following line in your NGINX proxy conf to see if that fixes your problem:
```
add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
```
so, it would become: 
```
add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-Application-Version';
```

However, I'm not sure why this is necessary, since my configuration, and others, works without the `x-application-version` header.

**Comment by akhiljalagam** [comment]
hey @xthursdayx 
appreciate your help.
after trying your changes, got a new cors issue and the following worked for me.
`add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-Application-Version,x-snjs-version';`

nginx/1.18.0
Debian GNU/Linux 11 (bullseye)

may be updating readme file helps all the folks like me. I can do a PR.
thank you very much. now extensions working for me.

**Comment by xthursdayx** [comment]
I think, for now at least, we'd probably rather not add any additional headers to the default NGINX config, unless they prove to be necessary for everyone to get the extensions to work. I haven't heard of anyone else needing to add the `X-Application-Version` and `X-SNJS-Version` headers to get their extensions to work, so for now, It's probably enough to just have this issue as a record of the fix, in case anyone else runs into the same problem.

**Comment by akhiljalagam** [comment]
maybe it's related to the browser.
my browser version is
`Google Chrome | 100.0.4896.88 (Official Build) (64-bit)`
chrome has enhanced security option enabled in settings.

**Comment by xthursdayx** [comment]
Interesting, could be. I've had more problems in general with Firefox than Chrome (with other self-hosted software, not Standard Notes extensions), but that could just be how I have FF set up. 

Anyway, feel free to make the PR if you'd like, and think this issue may be more widespread. I'm not repo owner anyway, so @iganeshk will have to make the call whether he wants to merge it or not.
