### ISSUE TITLE
Hosted Web Versions from "s.murrum.eu" re Down

### ISSUE THREAD

**Issue by Ryonez** [iganeshk/standardnotes-extensions#6]
Basically as the title states. I've learned that the web clients have to use the hosted version of the extensions, something that wasn't clear to me as this was meant to be about self hosting them.

So, while the desktop client is working, the web one isn't.

I suggest change this so you can point the client for extensions that that are being hosted by the person themselves.

For Moookino this would probably require him to set up his docker image to read a variable to the the host url and apply it to the extensions served.

**Comment by Ryonez** [comment]
Actually something is still wonky, because when I delete a local extension, I can't re-download it.

Here's my nginx config for the extensions using the docker container:
![image](https://user-images.githubusercontent.com/16157130/91978292-f7a68d00-ed77-11ea-8c14-056b6fec6454.png)

I stuck most of this together with this guide's help, expect I used docker images. Compose wasn't used at all.
In any case I need a break from this for the rest of my night, I've spent 4 hours on this, 3 of them trying to get the extensions to work.

**Comment by moookino** [comment]
@Ryonez my bad with docker image, please use repo for build your own image, i'll try to improve mine in the meantime
https://github.com/moookino/snext

**Comment by Ryonez** [comment]
Ahh, so that's what happened. Alright, Ill have to either spin up linux to compile this, figure out what's breaking pathing in the build, or make my own image.

Fun times >.<

**Comment by Ryonez** [comment]
Going to close this as there's multiple issues and I will move the docker related ones over to that repo.
