### ISSUE TITLE
Feature Request: Please add extensions-manager and batch-manager to the Repo

### ISSUE THREAD

**Issue by Ryonez** [iganeshk/standardnotes-extensions#7]
As it say in the title, I'd like to request the extensions-manager and batch-manager to be added to the repo.

It took me a while to narrow down the issue, but when replacing the `/extensions` part of the url, it removes access to the web docker image version of those two repos. So while all the files to these repo exist, the extension management tools cease working as they can't be accessed.

Currently I've just copied the app and dist folder from them over into my copy of the repo here, and it seems to have worked without issue. So I'd like to ask the be added to the repo to prevent needing to copy them in the future.

extensions-manager repo: https://github.com/sn-extensions/extensions-manager/tree/master
batch-manager repo: https://github.com/sn-extensions/batch-manager/tree/master

**Comment by gyaneesh** [comment]
I would suggest you to modify the utility to pull those two repos yourself since this seems to be an isolated issue concerning docker.
